Feat/product add page
Deva-Coders/inventario-frontend pull request #36
Opened 2024-08-20 14:36 UTC by fidelChoqueDev

## Description

create a record of the new item/product being. 
creating fields and buttons to add records

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Enhancement (improvement of an existing feature)
- [ ] Refactor (code change that neither fixes a bug nor adds a feature)
- [ ] Documentation (changes or additions to documentation)
- [ ] Other (please specify):

## Related Issues

 Related to [Trello Card 80 ](https://trello.com/c/sVCVIKYX) 

## Screenshots

![image](https://github.com/user-attachments/assets/e362b77d-02b9-4f46-88a4-5b09d7602ed2)

2024-08-20 14:58 UTC, Alejandro25AR commented
Debes cambiar la rama a la cual se hará _merge_ actualmente la tienes en `main` la tienes que pasar a `develop`

2024-08-20 15:01 UTC, Alejandro25AR requested changes
Debes cambiar la rama a la cual se hará _merge_ actualmente la tienes en `main` la tienes que pasar a `develop`

2024-08-20 20:08 UTC, MiguelDecode requested changes
Review spanglish code.

2024-08-20 20:08 UTC, MiguelDecode commented on src/components/ProductForm/ProductsAdd.module.css
> +.conteiner {
Here you have a typo error, i think.

2024-08-20 20:08 UTC, MiguelDecode commented on src/components/ProductForm/ProductsAdd.tsx
> +      <div className={style.conteiner}>
Same typo.

2024-08-20 20:08 UTC, MiguelDecode commented on src/components/ProductForm/ProductsAdd.tsx
Revisa el texto para no tener spanglish.

2024-08-20 20:08 UTC, MiguelDecode commented on src/components/ProductForm/ProductsAdd.tsx
Placeholder first letter in uppercase.

2024-08-20 20:08 UTC, MiguelDecode commented on src/components/ProductForm/ProductsAdd.tsx
> +              name="imagen"
Use english inside the code.

2024-08-21 14:07 UTC, Alejandro25AR commented on src/components/ProductForm/ProductsAdd.tsx
> +    UnitPrice: '',
UnitPrice debe ir en camalCase y quedar unitParice

2024-08-21 14:09 UTC, Alejandro25AR reviewed
Todo lo que ve el usuario debe estar en español. cambia los _labels_ y _placeholder_

2024-08-22 01:57 UTC, Alejandro25AR commented on src/components/ProductForm/ProductsAdd.tsx
>        <div className={style.conteiner}>
change conteiner by container

2024-08-22 01:57 UTC, Alejandro25AR commented on src/components/ProductForm/ProductsAdd.module.css
> +img{
Crea una clase o estos estilos se aplicaran en todas las etiquetas img del proyecto

2024-08-22 01:57 UTC, Alejandro25AR commented on src/components/ProductForm/ProductsAdd.module.css
> +form{
Crea una clase o estos estilos se aplicaran en todas las etiquetas form del proyecto

2024-08-22 01:57 UTC, Alejandro25AR commented on src/components/ProductForm/ProductsAdd.module.css
> +button{
Crea una clase o estos estilos se aplicaran en todas las etiquetas button del proyecto

2024-08-22 13:11 UTC, fidelChoqueDev commented on src/components/ProductForm/ProductsAdd.module.css
> +img{
okey, procedo. Pregunta: al estar img en "productsAdd.module.css" no afecta solo a este componente? ya que se utiliza module?

2024-08-22 13:22 UTC, MiguelDecode approved these changes

2024-08-22 13:24 UTC, MiguelDecode approved these changes

2024-08-22 14:26 UTC, MiguelDecode approved these changes

2024-08-22 15:04 UTC, Alejandro25AR approved these changes

2024-08-22 15:31 UTC, Alejandro25AR commented on src/components/ProductForm/ProductsAdd.module.css
> +img{
Tienes razón se aplican localmente, olvidaba que estabas aplicando los estilos por módulos

2024-08-23 02:26 UTC, merged